FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      ovmf \
      qemu-system-gui \
      qemu-system-x86 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /work
